/* ============ данные ============ */
const PHRASE=[{off:7,dur:.4},{off:12,dur:1.25},{off:10,dur:.42},{off:8,dur:.42},{off:7,dur:.42},{off:5,dur:.42},{off:3,dur:.42},{off:2,dur:.42},{off:0,dur:.42},{off:-1,dur:1.1,gap:.3},{off:8,dur:.4},{off:8,dur:.4},{off:7,dur:.5},{off:7,dur:1.7}];
const PIPE_OFFSETS=[12,10,8,7,5];
const KEYS=[
{name:"Ре минор",who:"куплет Кристины",tonic:146.83,peak:"вершина — ре (D4)",names:{"12":["ре","D4"],"10":["до","C4"],"8":["си♭","B♭3"],"7":["ля","A3"],"5":["соль","G3"],"3":["фа","F3"],"2":["ми","E3"],"0":["ре","D3"],"-1":["до#","C#3"]}},
{name:"Соль минор",who:"куплет Призрака",tonic:196,peak:"вершина — соль (G4)",names:{"12":["соль","G4"],"10":["фа","F4"],"8":["ми♭","E♭4"],"7":["ре","D4"],"5":["до","C4"],"3":["си♭","B♭3"],"2":["ля","A3"],"0":["соль","G3"],"-1":["фа#","F#3"]}},
{name:"Ми минор",who:"поют вдвоём",tonic:164.81,peak:"вершина — ми (E4)",names:{"12":["ми","E4"],"10":["ре","D4"],"8":["до","C4"],"7":["си","B3"],"5":["ля","A3"],"3":["соль","G3"],"2":["фа#","F#3"],"0":["ми","E3"],"-1":["ре#","D#3"]}}];
let currentKey=1,targetOff=12,mode="organ";
const freqOf=(k,off)=>KEYS[k].tonic*Math.pow(2,off/12);
let ctx=null,busNode=null,noiseBuf=null,modBuf=null;
async function ready(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC){setStatus("Браузер не поддерживает Web Audio.");return null}if(!ctx)ctx=new AC();if(ctx.state!=="running")try{await ctx.resume()}catch(e){}try{const s=ctx.createBufferSource();s.buffer=ctx.createBuffer(1,1,22050);s.connect(ctx.destination);s.start(0)}catch(e){}if(ctx.state!=="running"){setStatus("Звук заблокирован. Нажмите ещё раз или откройте страницу в Safari.");return null}setStatus("");return ctx}
function bus(ac){if(busNode)return busNode;const c=ac.createDynamicsCompressor();c.threshold.value=-14;c.ratio.value=6;c.attack.value=.004;c.release.value=.2;c.connect(ac.destination);busNode=c;return c}
function noise(ac){if(noiseBuf)return noiseBuf;const len=Math.floor(ac.sampleRate*.5);noiseBuf=ac.createBuffer(1,len,ac.sampleRate);const d=noiseBuf.getChannelData(0);for(let i=0;i<len;i++)d[i]=Math.random()*2-1;return noiseBuf}
function modNoise(ac){if(modBuf)return modBuf;const len=Math.floor(ac.sampleRate*4);modBuf=ac.createBuffer(1,len,ac.sampleRate);const d=modBuf.getChannelData(0),a=.9978;let v=0,max=0;for(let i=0;i<len;i++){v=a*v+(1-a)*(Math.random()*2-1);d[i]=v;if(Math.abs(v)>max)max=Math.abs(v)}if(max>0)for(let i=0;i<len;i++)d[i]/=max;return modBuf}
function playOrgan(ac,freq,dur,t0){const g=ac.createGain();g.connect(bus(ac));g.gain.setValueAtTime(.0001,t0);g.gain.exponentialRampToValueAtTime(.38,t0+.04);g.gain.setValueAtTime(.38,t0+dur*.65);g.gain.exponentialRampToValueAtTime(.0001,t0+dur);[[1,1],[2,.42],[3,.22],[4,.12],[6,.05]].forEach(([m,a])=>{const o=ac.createOscillator(),gg=ac.createGain();o.type="sine";o.frequency.value=freq*m;gg.gain.value=a;o.connect(gg);gg.connect(g);o.start(t0);o.stop(t0+dur+.05)})}
function playVoice(ac,freq,dur,t0,withF){const vStart=t0+(withF?.1:.015),tEnd=t0+dur;if(withF){const n=ac.createBufferSource();n.buffer=noise(ac);const f=ac.createBiquadFilter();f.type="bandpass";f.frequency.value=4500;f.Q.value=.6;const g=ac.createGain();g.gain.setValueAtTime(.0001,t0);g.gain.linearRampToValueAtTime(.1,t0+.04);g.gain.linearRampToValueAtTime(.0001,t0+.14);n.connect(f);f.connect(g);g.connect(bus(ac));n.start(t0);n.stop(t0+.16)}const osc=ac.createOscillator();osc.type="sawtooth";osc.frequency.setValueAtTime(freq*.972,vStart);osc.frequency.exponentialRampToValueAtTime(freq,vStart+.08);const lfo=ac.createOscillator(),lfoAmt=ac.createGain();lfo.frequency.value=5.4;lfoAmt.gain.setValueAtTime(0,vStart);lfoAmt.gain.linearRampToValueAtTime(freq*.013,vStart+.6);lfo.connect(lfoAmt);lfoAmt.connect(osc.frequency);lfo.start(vStart);lfo.stop(tEnd+.1);const jit=ac.createBufferSource(),jAmt=ac.createGain();jit.buffer=modNoise(ac);jit.loop=true;jAmt.gain.value=freq*.004;jit.connect(jAmt);jAmt.connect(osc.frequency);jit.start(vStart,Math.random()*3);jit.stop(tEnd+.1);const tilt=ac.createBiquadFilter();tilt.type="lowpass";tilt.frequency.value=3600;tilt.Q.value=.4;osc.connect(tilt);const shimmer=ac.createGain();shimmer.gain.value=1;const shm=ac.createBufferSource(),sAmt=ac.createGain();shm.buffer=modNoise(ac);shm.loop=true;sAmt.gain.value=.07;shm.connect(sAmt);sAmt.connect(shimmer.gain);shm.start(vStart,Math.random()*3);shm.stop(tEnd+.1);const vg=ac.createGain();shimmer.connect(vg);vg.connect(bus(ac));vg.gain.setValueAtTime(.0001,vStart);vg.gain.exponentialRampToValueAtTime(1.2,vStart+.09);vg.gain.setValueAtTime(1.2,t0+dur*.72);vg.gain.exponentialRampToValueAtTime(.0001,tEnd);[[530,4.5,1],[1840,8,.55],[2500,9,.22],[2850,14,.5],[3200,14,.28]].forEach(([f,q,g])=>{const bp=ac.createBiquadFilter(),gg=ac.createGain();bp.type="bandpass";bp.frequency.value=f;bp.Q.value=q;gg.gain.value=g;tilt.connect(bp);bp.connect(gg);gg.connect(shimmer)});const br=ac.createBufferSource(),bf=ac.createBiquadFilter(),bg=ac.createGain();br.buffer=noise(ac);br.loop=true;bf.type="bandpass";bf.frequency.value=2400;bf.Q.value=.8;bg.gain.setValueAtTime(.0001,vStart);bg.gain.linearRampToValueAtTime(.016,vStart+.12);bg.gain.linearRampToValueAtTime(.0001,tEnd);br.connect(bf);bf.connect(bg);bg.connect(bus(ac));br.start(vStart);br.stop(tEnd+.05);osc.start(vStart);osc.stop(tEnd+.05)}
function emit(ac,freq,dur,t0,withF){mode==="voice"?playVoice(ac,freq,dur,t0,withF!==false):playOrgan(ac,freq,dur,t0)}
let refUntil=0;function holdMic(ms){refUntil=Math.max(refUntil,performance.now()+ms+150)}
const $=id=>document.getElementById(id),statusEl=$("status");function setStatus(m){statusEl.textContent=m}
const keysEl=$("keys"),stripEl=$("strip"),pipesEl=$("pipes");
KEYS.forEach((k,i)=>{const b=document.createElement("button");b.className="key";b.innerHTML='<span class="kname">'+k.name+'</span><span class="kwho">'+k.who+'</span><span class="kpeak">'+k.peak+'</span>';b.addEventListener("click",()=>selectKey(i));keysEl.appendChild(b)});
function resetDetector(){if(typeof history!=="undefined")history.length=0;if(typeof smoothHz!=="undefined")smoothHz.length=0;if(typeof lastGood!=="undefined")lastGood=null;if(typeof lastGoodAt!=="undefined")lastGoodAt=0}
function selectKey(i){currentKey=i;resetDetector();Array.from(keysEl.children).forEach((el,n)=>el.classList.toggle("is-on",n===i));if(!KEYS[i].names[String(targetOff)])targetOff=12;drawPipes();drawStrip();drawTarget()}
function drawPipes(){const k=KEYS[currentKey];pipesEl.innerHTML="";const hi=freqOf(currentKey,PIPE_OFFSETS[0]),lo=freqOf(currentKey,PIPE_OFFSETS.at(-1));PIPE_OFFSETS.forEach(off=>{const f=freqOf(currentKey,off),[ru,sci]=k.names[String(off)],t=(hi-f)/(hi-lo),b=document.createElement("button");b.className="pipe"+(off===targetOff?" target":"");b.setAttribute("aria-label",ru+", "+sci);b.innerHTML='<div class="tube" style="height:'+(42+t*43)+'%"></div><div class="lbl"><div class="ru">'+ru+'</div><div class="sci">'+sci+'</div></div>';b.addEventListener("click",async()=>{targetOff=off;resetDetector();drawPipes();drawTarget();const ac=await ready();if(!ac)return;const dur=mode==="voice"?1.6:1.1;emit(ac,f,dur,ac.currentTime+.03,true);holdMic(dur*1000);const el=Array.from(pipesEl.children).find(p=>p.querySelector(".sci").textContent===sci);if(el){el.classList.add("sounding");setTimeout(()=>el.classList.remove("sounding"),dur*1000)}});pipesEl.appendChild(b)})}
function drawStrip(){const k=KEYS[currentKey];stripEl.innerHTML="";PHRASE.forEach(n=>{const c=document.createElement("span");c.className="chip"+(n.off===12?" peak":"");c.textContent=k.names[String(n.off)][0];stripEl.appendChild(c)})}
function drawTarget(){const [ru,sci]=KEYS[currentKey].names[String(targetOff)];$("targetName").textContent="Цель: "+ru+" · "+sci;$("targetHz").textContent=freqOf(currentKey,targetOff).toFixed(1)+" Гц"}
let timers=[];$("playPhrase").addEventListener("click",async()=>{const ac=await ready();if(!ac)return;timers.forEach(clearTimeout);timers=[];Array.from(stripEl.children).forEach(c=>c.classList.remove("on"));let t=ac.currentTime+.08,total=0;PHRASE.forEach((n,i)=>{emit(ac,freqOf(currentKey,n.off),n.dur*.95,t,i===0);const chip=stripEl.children[i],at=(t-ac.currentTime)*1000;timers.push(setTimeout(()=>chip.classList.add("on"),at));timers.push(setTimeout(()=>chip.classList.remove("on"),at+n.dur*1000));t+=n.dur+(n.gap||0);total=t-ac.currentTime});holdMic(total*1000)});
const organBtn=$("modeOrgan"),voiceBtn=$("modeVoice");function setMode(m){mode=m;organBtn.classList.toggle("is-on",m==="organ");voiceBtn.classList.toggle("is-on",m==="voice");organBtn.setAttribute("aria-pressed",m==="organ");voiceBtn.setAttribute("aria-pressed",m==="voice")}
organBtn.addEventListener("click",()=>setMode("organ"));voiceBtn.addEventListener("click",async()=>{setMode("voice");const ac=await ready();if(!ac)return;emit(ac,freqOf(currentKey,targetOff),1.9,ac.currentTime+.03,true);holdMic(1900)});
