const W=2048,yinBuf=new Float32Array(W);
function detectPitch(buf,sr){let rms=0;for(let i=0;i<buf.length;i++)rms+=buf[i]*buf[i];rms=Math.sqrt(rms/buf.length);if(rms<.006)return null;const tauMin=Math.floor(sr/1000),tauMax=Math.min(W,Math.floor(sr/65));yinBuf[0]=1;let running=0;for(let tau=1;tau<tauMax;tau++){let sum=0;for(let i=0;i<W;i++){const d=buf[i]-buf[i+tau];sum+=d*d}running+=sum;yinBuf[tau]=running===0?1:sum*tau/running}let tau=-1;for(let t=tauMin;t<tauMax;t++){if(yinBuf[t]<.15){while(t+1<tauMax&&yinBuf[t+1]<yinBuf[t])t++;tau=t;break}}if(tau<0){let best=1,bi=-1;for(let t=tauMin;t<tauMax;t++)if(yinBuf[t]<best){best=yinBuf[t];bi=t}if(bi<0||best>.5)return null;tau=bi}let better=tau;if(tau>0&&tau<tauMax-1){const a=yinBuf[tau-1],b=yinBuf[tau],c=yinBuf[tau+1],den=2*(2*b-a-c);if(den!==0)better=tau+(c-a)/den}const hz=sr/better;return hz<60||hz>1200?null:{hz,clarity:1-yinBuf[tau],rms}}
let micStream=null,analyser=null,micBuf=null,rafId=null,micOn=false,lastRun=0;
const history=[],smoothHz=[];let lastGood=null,lastGoodAt=0;
let sessionState="idle",sessionStart=0,sessionSamples=[],countdownTimer=null;
const SESSION_MS=3000,COUNTDOWN_MS=700;
function median(a){if(!a.length)return null;const b=a.slice().sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2}
function resetDetector(){history.length=0;smoothHz.length=0;lastGood=null;lastGoodAt=0;sessionSamples=[];if(sessionState!=="countdown")sessionState="idle";const fill=$("listenFill");if(fill)fill.style.width="0%"}
function setListeningUI(text,pct){$("listenText").textContent=text;$("listenFill").style.width=Math.max(0,Math.min(100,pct))+"%"}
function stopMic(){micOn=false;sessionState="idle";if(countdownTimer)clearTimeout(countdownTimer);if(rafId)cancelAnimationFrame(rafId);if(micStream)micStream.getTracks().forEach(t=>t.stop());micStream=null;analyser=null;$("micBtn").textContent="Включить микрофон";$("listenBtn").disabled=true;$("needle").className="needle idle";$("needle").style.left="50%";$("vCents").textContent="—";$("vHz").textContent="—";$("vStab").textContent="—";$("verdict").textContent="Микрофон выключен.";setListeningUI("Сначала включите микрофон",0)}
$("micBtn").addEventListener("click",async()=>{if(micOn){stopMic();return}const ac=await ready();if(!ac)return;if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){setStatus("Браузер не даёт доступ к микрофону на этой странице.");return}try{try{micStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1}})}catch(e){micStream=await navigator.mediaDevices.getUserMedia({audio:true})}}catch(e){setStatus(e&&e.name==="NotAllowedError"?"Доступ к микрофону запрещён. Откройте страницу в Safari и разрешите микрофон.":"Микрофон не включился: "+(e.name||e));return}const src=ac.createMediaStreamSource(micStream);analyser=ac.createAnalyser();analyser.fftSize=4096;micBuf=new Float32Array(analyser.fftSize);src.connect(analyser);micOn=true;resetDetector();$("micBtn").textContent="Выключить микрофон";$("listenBtn").disabled=false;$("verdict").textContent="Микрофон готов. Послушайте эталон и нажмите «Слушать 3 секунды».";setListeningUI("Готов к попытке",0);setStatus("");loop()});
$("listenBtn").addEventListener("click",()=>{if(!micOn||sessionState!=="idle")return;if(performance.now()<refUntil){$("verdict").textContent="Подождите, пока закончится эталон.";return}resetDetector();sessionState="countdown";$("listenBtn").disabled=true;setListeningUI("Приготовьтесь… вдох и начинайте «ааа»",0);$("verdict").textContent="Сейчас начнётся трёхсекундный замер.";countdownTimer=setTimeout(()=>{sessionState="recording";sessionStart=performance.now();sessionSamples=[];smoothHz.length=0;history.length=0;setListeningUI("Держите ноту: 3,0 с",0);$("verdict").innerHTML="<b>Пойте и держите ровно.</b> Не прекращайте до конца полосы."},COUNTDOWN_MS)});
function finishSession(){sessionState="idle";$("listenBtn").disabled=false;setListeningUI("Попытка завершена — можно повторить",100);if(sessionSamples.length<12){$("verdict").innerHTML='<span class="warn">Не хватило устойчивого звука.</span> Пойте чуть громче и держите «ааа» все три секунды.';return}const cents=sessionSamples.map(x=>x.cents),avg=cents.reduce((a,b)=>a+b,0)/cents.length,absAvg=cents.reduce((a,b)=>a+Math.abs(b),0)/cents.length,in10=Math.round(cents.filter(x=>Math.abs(x)<=10).length/cents.length*100),in20=Math.round(cents.filter(x=>Math.abs(x)<=20).length/cents.length*100),coverage=Math.round(sessionSamples.length/(SESSION_MS/40)*100);$("vCents").textContent=(avg>0?"+":"")+avg.toFixed(0)+"¢";$("vStab").textContent=in20+"%";let quality=in10>=75?"Отлично":in20>=70?"Хорошо":in20>=45?"Нестабильно":"Нужно повторить";$("verdict").innerHTML="<b>"+quality+".</b> Среднее отклонение "+(avg>0?"+":"")+avg.toFixed(0)+" центов; в пределах ±10¢ — "+in10+"%, в пределах ±20¢ — "+in20+"%. Уверенный сигнал был примерно "+Math.min(100,coverage)+"% времени."}
function showMeasurement(hz,cents,oct,now){const needle=$("needle"),clamped=Math.max(-50,Math.min(50,cents));needle.className="needle"+(Math.abs(cents)<=10?" good":"");needle.style.left=((clamped+50)).toFixed(1)+"%";$("vHz").textContent=hz.toFixed(1)+" Гц";$("vCents").textContent=(cents>0?"+":"")+cents.toFixed(0)+"¢";history.push({t:now,cents});while(history.length&&now-history[0].t>2000)history.shift();if(history.length>8)$("vStab").textContent=Math.round(history.filter(x=>Math.abs(x.cents)<=20).length/history.length*100)+"%";if(sessionState!=="recording"){const [ru]=KEYS[currentKey].names[String(targetOff)];let msg=Math.abs(cents)<=10?"<b>Точно.</b>":cents<0?"Низите на "+Math.abs(cents).toFixed(0)+" центов.":"Завышаете на "+cents.toFixed(0)+" центов.";if(oct!==0)msg+=' <span class="warn">Это '+ru+' октавой '+(oct<0?'ниже':'выше')+'.</span>';$("verdict").innerHTML=msg}}
function loop(){if(!micOn)return;rafId=requestAnimationFrame(loop);const now=performance.now();if(now-lastRun<40)return;lastRun=now;if(sessionState==="recording"){const elapsed=now-sessionStart,pct=elapsed/SESSION_MS*100;setListeningUI("Держите ноту: "+Math.max(0,(SESSION_MS-elapsed)/1000).toFixed(1)+" с",pct);if(elapsed>=SESSION_MS){finishSession();return}}if(now<refUntil)return;analyser.getFloatTimeDomainData(micBuf);const res=detectPitch(micBuf,ctx.sampleRate);if(!res||res.clarity<.5){if(sessionState==="recording")return;if(lastGood&&now-lastGoodAt<650){$("verdict").textContent="Держу последнее уверенное измерение…";return}$("needle").className="needle idle";$("verdict").textContent="Жду устойчивый голос.";return}smoothHz.push(res.hz);if(smoothHz.length>7)smoothHz.shift();const hz=median(smoothHz);lastGood=hz;lastGoodAt=now;const target=freqOf(currentKey,targetOff),raw=1200*Math.log2(hz/target),oct=Math.round(raw/1200),cents=raw-oct*1200;showMeasurement(hz,cents,oct,now);if(sessionState==="recording")sessionSamples.push({cents,hz,oct})}
window.addEventListener("error",e=>setStatus("Ошибка запуска: "+(e.message||"неизвестная ошибка")+". Обновите страницу."));selectKey(currentKey);setStatus("");